#include "moduleout.h"

#include "audiodeviceprovider.h"
#include "buffer.h"
#include "clock.h"
#include "factory/synthprofactory.h"
#include "inport.h"
#include "sequencer.h"

#include <QAudioOutput>
#include <QDebug>

ModuleOut::ModuleOut(QIODevice* device, QAudioOutput* audioOutput, QObject* parent)
    : Module(parent)
    , m_device(device)
    , m_audioOutput(audioOutput)
    // , m_generationBuffer(new char[GENERATION_BUFFER_SIZE])
    // , m_generationBufferPointer(0)
    , m_nbGeneratedBytesRemaining(0)
    , m_sequencer(Sequencer::instance())
    , m_manageSound(false)
{
    // m_generationBufferPointer = m_generationBuffer; // Strange, bug if initialized above...

}

ModuleOut::~ModuleOut()
{
}

void ModuleOut::initialize(SynthProFactory* factory)
{
    m_generationBuffer = new char[GENERATION_BUFFER_SIZE];
    m_generationBufferPointer = m_generationBuffer; // Strange, bug if initialized above...

    for (int i = 0; i < GENERATION_BUFFER_SIZE; i++) {
        m_generationBuffer[i] = 0;
    }

    if (factory) {
        // Creation of an Input.
        m_inPort = factory->createInPortReplicable(this);
        m_inports.append(m_inPort);

        // Register to a fast timer to the Clock.
        Clock& clock = Clock::instance();
        clock.registerFastClock(this);
    }
}

void ModuleOut::setSoundManagement(bool state)
{
    m_manageSound = state;
}

void ModuleOut::timerExpired()
{
    if (!m_manageSound) {
        return;
    }
    // qDebug() << "Timer Expired Module Out";
    // qDebug() << m_audioOutput->bytesFree();

    int fillCounter = 0;
    qint64 sizeWritten = 1;
    int nbBytesNeededByOutput = m_audioOutput->bytesFree();
    while (((fillCounter < FILL_COUNTER_MAX) && (nbBytesNeededByOutput > 0)) && (sizeWritten > 0)) {
        // qWarning() << "Needing " << nbBytesNeededByOutput << ". Counter = " << fillCounter;
        // Check if we have some generated bytes left in order to feed the output.
        if (m_nbGeneratedBytesRemaining > 0) {

            // We have some bytes left in our buffer. Is it enough ?
            if (m_nbGeneratedBytesRemaining >= nbBytesNeededByOutput) {
                // We have more than enough. We send only what is needed.
                // qWarning() << "Trying to write : " << nbBytesNeededByOutput;
                sizeWritten = m_device->write(m_generationBufferPointer, nbBytesNeededByOutput);
            } else {
                // We don't have enough. We send what we have for now.
                // qWarning() << "Trying to write : " << m_nbGeneratedBytesRemaining;
                sizeWritten = m_device->write(m_generationBufferPointer, m_nbGeneratedBytesRemaining);
            }
            m_generationBufferPointer += sizeWritten;
            m_nbGeneratedBytesRemaining -= sizeWritten;

            // qWarning() << "Actually written : " << sizeWritten;
            // nbBytesNeededByOutput -= sizeWritten;
            nbBytesNeededByOutput = m_audioOutput->bytesFree();

        } else {
            // We don't have any bytes in our buffer. We need to generate data.
            // generate(m_generationBuffer, GENERATION_BUFFER_SIZE);
            // We call the sequencer for it to process all the modules.
            m_sequencer.process();

            // Now we copy our InPort to the generationBuffer. A conversion is needed.
            qreal* data = m_inPort->buffer()->data();
            // qDebug() << m_inPort->buffer()->length();
            for (int i = 0, size = m_inPort->buffer()->length(); i < size; i+=2) {
                int nb = data[i];
                // qDebug() << data[i];
                m_generationBuffer[i] = nb / 256;
                m_generationBuffer[i + 1] = nb % 255;
                // m_generationBuffer[i] = 0;
                // m_generationBuffer[i + 1] = 0;
            }

            m_generationBufferPointer = m_generationBuffer;
            m_nbGeneratedBytesRemaining = GENERATION_BUFFER_SIZE;
            // qWarning() << "Generating";
        }

        fillCounter++;
    }

    if (fillCounter >= FILL_COUNTER_MAX) {
        qWarning() << "Unable to feed the sound card enough !";
    }
    if (sizeWritten == 0) {
        qWarning() << "Size written = 0... Abnormal.";
    }
    if (sizeWritten < 0) {
        qWarning() << "Error while writing to the sound card !";
    }
}

void ModuleOut::ownProcess()
{
    // TODO
}
